default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bootbook_development

test:
  <<: *default
  database: bootbook_test

production:
  <<: *default
  database: bootbook_production
